### ISSUE TITLE
Python2 with data containing umlauts – UnicodeEncodeError: 'ascii' codec can't encode character ... ordinal not in range(128)

### ISSUE THREAD

**Issue by Hukkinen** [hbuschme/TextGridTools#15]
If you get this error with python2, switch to python3, as that defaults internally to utf-8, and seems to work.

I was trying to open utf-8 TextGrid files, which have Finnish umlauts (ä,ö, and å for Swedish). Non-umlaut files work fine.

TextGridTools' internal representation(?) of ascii range(128) excludes the umlauts somewhere on the way.

Hence, alas:

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 69: ordinal not in range(128)

import tgt
tg=tgt.read_textgrid('t.tg')
tg.get_tier_names()
Out[55]: [u'utterance', u'word', u'morph', u'phone']

In [57]: tg.get_tier_by_name(u'phone')
Out[57]: ---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
/home/jh/miniconda3/envs/deep-voice-conversion/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    697                 type_pprinters=self.type_printers,
    698                 deferred_pprinters=self.deferred_printers)
--> 699             printer.pretty(obj)
    700             printer.flush()
    701             return stream.getvalue()

/home/jh/miniconda3/envs/deep-voice-conversion/lib/python2.7/site-packages/IPython/lib/pretty.pyc in pretty(self, obj)
    401                         if cls is not object \
    402                                 and callable(cls.__dict__.get('__repr__')):
--> 403                             return _repr_pprint(obj, self, cycle)
    404 
    405             return _default_pprint(obj, self, cycle)

/home/jh/miniconda3/envs/deep-voice-conversion/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _repr_pprint(obj, p, cycle)
    701     """A pprint that just redirects to the normal repr function."""
    702     # Find newlines and replace them with p.break_()
--> 703     output = repr(obj)
    704     for idx,output_line in enumerate(output.splitlines()):
    705         if idx:

/home/jh/miniconda3/envs/deep-voice-conversion/lib/python2.7/site-packages/tgt/core.pyc in __repr__(self)
    461     def __repr__(self):
    462         return '{0}(start_time={1}, end_time={2}, name="{3}", objects={4})'.format(self.__class__.__name__,
--> 463             self.start_time, self.end_time, self.name, self._objects)
    464 
    465 

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 24: ordinal not in range(128)

--- clip: t.tg ---

    item[4]:
        class = "IntervalTier"
        name = "phone"
        xmin = 0.000
        xmax = 33.024
        intervals: size = 174

        intervals [47]:
            xmin = 3.928
            xmax = 4.112
            text = "ä"

       intervals [118]:
            xmin = 9.232
            xmax = 9.568
            text = "ö"
``

**Comment by hbuschme** [comment]
Working with UTF-8 encoded strings in Python2 is difficult in general. However, we have successfully used TextGridTools with Python2 and UTF-8 encoded TextGrid files in the past. The problem here is not TextGridTools specific. One work-around is to explicitly convert strings before (e.g.) printing them, using the unicode function. Here is an example:

```
import tgt
tg = tgt.read_textgrid('t.tg')
tg.get_tier_names()
for interval in tg.get_tier_by_name('hallo'):
	print(unicode(interval.text))
```
