### ISSUE TITLE
[bug] Tier entries that have blank labels are not read

### ISSUE THREAD

**Issue by SolomidHero** [hbuschme/TextGridTools#20]
Like in https://github.com/timmahrt/praatIO/issues/29

**Comment by hbuschme** [comment]
Similar to praatIO, TextGridTools' read_textgrid function has a default argument `include_empty_intervals=False`. If you want empty intervals to be read, set it to `true`, like so:
```
tgt.read_textgrid('Desktop/mytextgrid.TextGrid', nclude_empty_intervals=True)
```
Defaulting this argument to `false` is sensible in our opinion as we – and others we know – usually use empty intervals as blank spaces between meaningful, labeled intervals. 

In the future, we will however provide a description in the docstring.

Thanks for the hint, I hope my answer is helpful.
