### ISSUE TITLE
Is there any sample for writing meta data into textgrid file ?

### ISSUE THREAD

**Issue by kehuantiantang** [hbuschme/TextGridTools#21]
Hello, I am working on music transcriptions. I have some data which contain "start, end,  word" record like that:
```
23.970000	24.146741	life
24.323482	24.500223	is
24.676964	24.853704	a
25.030445	25.383927	mo
25.383927	25.737409	ment
25.737409	25.914150	in
```
Can I create TextGrid ojbect and write them to `.textgrid` file and visualize in Praat ?  Thanks a lot.

**Comment by mwlodarczak** [comment]
On 1/26/22 09:37, Sober wrote:
> Hello, I am working on music transcriptions. I have some data which 
> contain "start, end, word" record like that:
> 
> |23.970000 24.146741 life 24.323482 24.500223 is 24.676964 24.853704 a 
> 25.030445 25.383927 mo 25.383927 25.737409 ment 25.737409 25.914150 in |
> 
> Can I create TextGrid ojbect and write them to |.textgrid| file and 
> visualize in Praat ? Thanks a lot.

Yes, of course. You just need to create an Interval object for each line 
in the input file, store it in an IntervalTier, add that to a TextGrid 
object and save the result to a file.

So basically something like this (untested code!):

tier = tgt.IntervalTier(name='tier1')
for l in file:
     tier.add_annotations(tgt.Interval(*l.strip().split()))
tg = tgt.TextGrid()
tg.add_tier(tier)
tgt.write_to_file(tg, 'test.TextGrid')

Best wishes,
Marcin

**Comment by kehuantiantang** [comment]
Thank you so much for your sample. I tried to implement according to your script, this is my version:
```
def text2textGrid(source):
    f = open(source, 'r')
    lines = f.readlines()
    tier = tgt.IntervalTier(name='words')

    for line in lines:
        start, end, text = line.strip('\n').split('\t')
        print(start, end, text)
        tier.add_annotation(tgt.Interval(start_time = float(start), end_time = float(start), text = text))
    f.close()

    tg = tgt.TextGrid()
    tg.add_tier(tier)
    tgt.io.write_to_file(tg, 'test.TextGrid', format='long')
```
This is my meta file:
```
5.822000	6.112323	hey
6.209097	6.499419	hey
12.015548	12.305871	hey
12.402645	12.692968	hey
22.128452	22.225226	some
22.322000	22.418774	times
22.515548	22.612323	i
```
The result of following code is so strange:
```
File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0.0
xmax = 221.967161
tiers? <exists>
size = 1
item []:
	item [1]:
		class = "IntervalTier"
		name = "words"
		xmin = 0.0
		xmax = 221.967161
		intervals: size = 860
		intervals [1]:
			xmin = 0.0
			xmax = 5.822
			text = ""
		intervals [2]:
			xmin = 5.822
			xmax = 6.209097
			text = ""
		intervals [3]:
			xmin = 5.822
			xmax = 5.822
			text = "hey"
		intervals [4]:
			xmin = 6.209097
			xmax = 12.015548
			text = ""
		intervals [5]:
			xmin = 6.209097
			xmax = 6.209097
			text = "hey"
		intervals [6]:
			xmin = 12.015548
			xmax = 12.402645
			text = ""
		intervals [7]:
			xmin = 12.015548
			xmax = 12.015548
			text = "hey"
		intervals [8]:
			xmin = 12.402645
			xmax = 22.128452
			text = ""
		intervals [9]:
			xmin = 12.402645
			xmax = 12.402645
			text = "hey"
		intervals [10]:
			xmin = 22.128452
			xmax = 22.322
			text = ""
		intervals [11]:
			xmin = 22.128452
			xmax = 22.128452
			text = "some"
		intervals [12]:
			xmin = 22.322
			xmax = 22.515548
			text = ""
		intervals [13]:
			xmin = 22.322
			xmax = 22.322
			text = "times"
		intervals [14]:
			xmin = 22.515548
			xmax = 22.709097
			text = ""
		intervals [15]:
			xmin = 22.515548
			xmax = 22.515548
			text = "i"
		intervals [16]:
			xmin = 22.709097
			xmax = 22.902645
			text = ""
```
The start (xmin) and end (xmax) for text interval is same. It seems like pause duration is wrongly insert. Should I manually calculate the pause part and add into Interval class ?

**Comment by mwlodarczak** [comment]
On 28 Jan 2022, at 08:55, Sober ***@***.***> wrote:
> 
>         tier.add_annotation(tgt.Interval(start_time = float(start), end_time = float(start), text = text))

You probably want to say end_time = float(end).
Marcin

**Comment by kehuantiantang** [comment]
This is the snippet of writing the meta data into .textgrid according to your comment. I test it and it works well, thank you so much for help.
```python
def text2textGrid_Lab(source, target, to_lab = False):
    def operator(s, t):
        filename = osp.split(s)[-1].split('.')[0]
        f = open(s, 'r')
        lines = f.readlines()
        tier = tgt.IntervalTier(name='words')
        texts = []
        for line in lines:
            start_time, end_time, text = line.strip('\n').split('\t')
            tier.add_annotation(tgt.Interval(start_time = float(start_time), end_time = float(end_time), text = text))
            texts.append(text)
        f.close()

        tg = tgt.TextGrid()
        tg.add_tier(tier)
        tgt.io.write_to_file(tg, osp.join(t, '%s.TextGrid'%filename), format='long')

        if to_lab:
            with open(osp.join(t, '%s.lab'%filename), 'w', encoding='utf-8') as f:
                f.write(' '.join(texts))

    operator(source, target)
```

**Comment by Approximetal** [comment]
> This is the snippet of writing the meta data into .textgrid according to your comment. I test it and it works well, thank you so much for help.
> 
> ```python
> def text2textGrid_Lab(source, target, to_lab = False):
>     def operator(s, t):
>         filename = osp.split(s)[-1].split('.')[0]
>         f = open(s, 'r')
>         lines = f.readlines()
>         tier = tgt.IntervalTier(name='words')
>         texts = []
>         for line in lines:
>             start_time, end_time, text = line.strip('\n').split('\t')
>             tier.add_annotation(tgt.Interval(start_time = float(start_time), end_time = float(end_time), text = text))
>             texts.append(text)
>         f.close()
> 
>         tg = tgt.TextGrid()
>         tg.add_tier(tier)
>         tgt.io.write_to_file(tg, osp.join(t, '%s.TextGrid'%filename), format='long')
> 
>         if to_lab:
>             with open(osp.join(t, '%s.lab'%filename), 'w', encoding='utf-8') as f:
>                 f.write(' '.join(texts))
> 
>     operator(source, target)
> ```

May I ask what is `osp` ?

**Comment by mwlodarczak** [comment]
> On 20 Nov 2023, at 04:14, Approximetal ***@***.***> wrote:
> 
> May I ask what is osp ?

Is it possible that you are importing os.path and naming it osp (`import os.path as osp`) somewhere else in your code?

Best wishes,
Marcin

**Comment by kehuantiantang** [comment]
Yes, you are right.

**Comment by kehuantiantang** [comment]
> On 20 Nov 2023, at 04:14, Approximetal ***@***.***> wrote: May I ask what is osp ?
> Is it possible that you are importing os.path and naming it osp (`import os.path as osp`) somewhere else in your code? Best wishes, Marcin



> On 20 Nov 2023, at 04:14, Approximetal ***@***.***> wrote: May I ask what is osp ?
> Is it possible that you are importing os.path and naming it osp (`import os.path as osp`) somewhere else in your code? Best wishes, Marcin

Yes, you are right.
